version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DB_NAME=newshub
      - PORT=8080
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_USE_SSL=false
      - MINIO_BUCKET_NAME=newshub-media
    depends_on:
      - mongodb
      - minio

  # 添加爬虫服务
  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    restart: always
    environment:
      - PORT=8001
      - LOG_LEVEL=INFO
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_USE_SSL=false
      - MINIO_BUCKET_NAME=newshub-media
    ports:
      - "8001:8001"
    volumes:
      - ./crawler-service:/app
      - crawler_logs:/app/logs
    depends_on:
      - mongodb
      - minio

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - crawler

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=newshub
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"

  # MinIO 对象存储服务
  minio:
    image: minio/minio:latest
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
      - MINIO_DOMAIN=localhost
    ports:
      - "9000:9000"  # API端口
      - "9001:9001"  # 控制台端口
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO 初始化服务
  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    volumes:
      - ./init-minio.sh:/init-minio.sh
    entrypoint: >
      /bin/sh -c "
      chmod +x /init-minio.sh &&
      /init-minio.sh
      "
    restart: "no"

volumes:
  mongodb_data:
  crawler_logs:
  minio_data: