version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DB_NAME=newshub
      - PORT=8080
    depends_on:
      - mongodb

  # 添加爬虫服务
  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    restart: always
    environment:
      - PORT=8001
      - LOG_LEVEL=INFO
    ports:
      - "8001:8001"
    volumes:
      - ./crawler-service:/app
      - crawler_logs:/app/logs
    depends_on:
      - mongodb

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - crawler

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=newshub
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
  crawler_logs: