version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DB_NAME=newshub
      - PORT=8080
    depends_on:
      - mongodb

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27015:27017"

volumes:
  mongodb_data: