version: '3.8'

services:
  # MinIO 对象存储服务
  minio:
    image: minio/minio:latest
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
      - MINIO_DOMAIN=localhost
    ports:
      - "9000:9000"  # API端口
      - "9001:9001"  # 控制台端口
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio-network

  # MinIO 初始化服务
  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    volumes:
      - ./init-minio.sh:/init-minio.sh
    entrypoint: >
      /bin/sh -c "
      chmod +x /init-minio.sh &&
      /init-minio.sh
      "
    restart: "no"
    networks:
      - minio-network

volumes:
  minio_data:

networks:
  minio-network:
    driver: bridge