FROM golang:1.21-alpine

WORKDIR /app

# 安装依赖
COPY server/go.mod server/go.sum ./
RUN go mod download

# 复制源代码
COPY server/ ./

# 编译
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

EXPOSE 8080

CMD ["./main"]